# swagger setting
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


#h2 setting
  datasource:
    #url: jdbc:h2:tcp://localhost/~/assignment #local
    url: jdbc:h2:mem:assignment # inmemory
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
        
# info
kakao:
  id: 39657f32752e187ca3c9b28c5e6a507b
  url: https://dapi.kakao.com/v2/local/search/keyword.json
  
naver:
  id: HZUyIjQHWkfOKMy03BBo
  secret: XKmri36pWC
  url: https://openapi.naver.com/v1/search/local.json